name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Run Spotless check
      run: mvn spotless:check
   
    - name: Show JAVA_HOME inside Snyk container
      run: docker run --rm snyk/snyk:maven-3-jdk-11 env | grep JAVA_HOME
    - name: list fiel for debugging
      run: |
        pwd
        ls -R
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-output=snyk.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
          sarif_file: snyk.sarif
