name: Example workflow for Maven using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          JAVA_HOME:  /opt/java/openjdk
      - name: Run Snyk Test
        id: snyk_test
        uses: snyk/actions/maven@master
        continue-on-error: true       
        with:
         command: test
         severity-threshold: high  
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Monitor
        if: ${{ steps.snyk_test.outcome == 'success' }}
        uses: snyk/actions/maven@master
        with:
         command: monitor
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
