name: Example workflow for Maven using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          JAVA_HOME:  /opt/java/openjdk
      - name: Run Snyk Monitor if no high severity
        continue-on-error: true
        run: |
          docker run --rm -v ${{ github.workspace }}:/project -w /project snyk/snyk:maven-3-jdk-11 test --all-projects --json > snyk_result.json || true
          HIGH_COUNT=$(jq '.vulnerabilities | map(select(.severity=="high")) | length' snyk_result.json)
          echo "High vulnerabilities found: $HIGH_COUNT"
          if [ "$HIGH_COUNT" -eq 0 ]; then
          echo "No high vulnerabilities, running monitor..."
          docker run --rm -v ${{ github.workspace }}:/project -w /project snyk/snyk:maven-3-jdk-11 monitor
          else
            echo "High vulnerabilities found, skipping monitor."
          fi
          env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
